<?php session_start();
 echo "ADMIN_ACCOUNT_USERID: ".$_SESSION["ADMIN_ACCOUNT_USERID"]."<br/>";
 echo "ADMIN_ACCOUNT_ROLEID: ".$_SESSION["ADMIN_ACCOUNT_ROLEID"]."<br/>";
 echo "ADMIN_ACCOUNT_ROLENAME: ".$_SESSION["ADMIN_ACCOUNT_ROLENAME"]."<br/>";
 echo "ADMIN_ACCOUNT_SURNAME: ".$_SESSION["ADMIN_ACCOUNT_SURNAME"]."<br/>";
 echo "ADMIN_ACCOUNT_NAME: ".$_SESSION["ADMIN_ACCOUNT_NAME"]."<br/>";
 echo "ADMIN_ACCOUNT_GENDER: ".$_SESSION["ADMIN_ACCOUNT_GENDER"]."<br/>";
 echo "ADMIN_ACCOUNT_EMAIL: ".$_SESSION["ADMIN_ACCOUNT_EMAIL"]."<br/>";
 echo "ADMIN_ACCOUNT_MOBCODE: ".$_SESSION["ADMIN_ACCOUNT_MOBCODE"]."<br/>";
 echo "ADMIN_ACCOUNT_MOBILE: ".$_SESSION["ADMIN_ACCOUNT_MOBILE"]."<br/>";
 echo "ADMIN_ACCOUNT_USERNAME: ".$_SESSION["ADMIN_ACCOUNT_USERNAME"]."<br/>";
 echo "ADMIN_ACCOUNT_ACTIVE: ".$_SESSION["ADMIN_ACCOUNT_ACTIVE"]."<br/>";
 echo "ADMIN_ACCOUNT_CREATEDON: ".$_SESSION["ADMIN_ACCOUNT_CREATEDON"]."<br/>";
 echo "ADMIN_ACCOUNT_ACCPERMISSIONS: ".$_SESSION["ADMIN_ACCOUNT_ACCPERMISSIONS"];

?>